/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dewafer.sudoku2

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun positionTest() {

        print("  ")
        (0 until 9).forEach {
            print("$it".padStart(4))
            if (it % 3 == 2) print(" | ") else print("   ")
        }

        println()
        println("-".repeat(64))

        (0 until 81).forEach {
            if (it % 9 == 0) print("${it / 9}|")
            print("$it".padStart(4))
            if (it % 3 == 2) print(" | ") else print("   ")
            if (it % 9 == 8) println()
            if (it % 27 == 26) println("-".repeat(64))
        }

        val positions = (0..8).flatMap { y -> (0..8).map { x -> Position(x, y) } }.toList()
        for (p in positions) {
            println("${p.toBoxIndex()}: $p, " +
                    "same col: ${p.sameColBoxIndices().toList()}, " +
                    "same row: ${p.sameRowBoxIndices().toList()}, " +
                    "same group: ${p.toGroupIndex().sameGroupBoxIndices().toList()}")
        }
    }
}

